### ISSUE TITLE
ООП и диаграммы классов UML

### ISSUE THREAD

**Issue by abel-nast** [abel-nast/prog_lazareva#1]
@antosha417 
я сделала задания по теме ООП и диаграммы классов UML
(все находится в соответствующей папке, задание по арифметическим драконам в одноименной папке)

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

Добавь больше врагов.

Пока ставлю тебе 0,8  за задачу, чтобы поднять поправь код. Умножаю на 0,7 за сдачу после делайна

**Comment by abel-nast** [comment]
Я сделала одного из троллей, указанных в задании, как делать остальных не очень понимаю.
https://github.com/abel-nast/prog_lazareva/blob/master/%D0%90%D1%80%D0%B8%D1%84%D0%BC%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5%20%D0%B4%D1%80%D0%B0%D0%BA%D0%BE%D0%BD%D1%8B/enemies.py

**Comment by antosha417** [comment]
Что не понятно? Задай вопрос конкретней

**Comment by abel-nast** [comment]
Ну, я не очень представляю себе алгоритм для поиска простых множителей.

**Comment by antosha417** [comment]
Проверь все числа пользователя на простату, просто проверяя, что введенные не деляться нацело ни на что до корня.
Потом проверь, что их перемножение даёт твоё число
