### ISSUE TITLE
Черепаха

### ISSUE THREAD

**Issue by abel-nast** [abel-nast/prog_lazareva#2]
@antosha417
[https://github.com/abel-nast/prog_lazareva/commit/5f96d1b2407cb357805fd21b2de34da22b8ff93f](url)
загрузила с 1 по 8 задания.

**Comment by antosha417** [comment]
Нужно делать задания про фракталы, это важно

Пока ставлю тебе  0,6 за задачу, чтобы поднять поправь код.
