### ISSUE TITLE
Лопни шарик

### ISSUE THREAD

**Issue by abel-nast** [abel-nast/prog_lazareva#3]
@antosha417
Сделаны задания 1-4 из блока "Лопни шарик". Файлы пронумерованы аналогично заданиям.
https://github.com/abel-nast/prog_lazareva/tree/master/tkinter

**Comment by antosha417** [comment]
* Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
* Убери весь код верхнего уровня в функции

Пока ставлю тебе 0,8  за задачу, чтобы поднять поправь код.
Умножаю оценку на 0,7 за сдачу после дедлайна.
